### ISSUE TITLE
Add NuGet keyword "MSBuildLocator"

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/MSBuildLocator#101]
I just told @BenVillalobos to add a reference to "MSBuildLocator" and quite reasonably he typed `msbuildlocator` into NuGet search, which found [Nuke.MSBuildLocator](https://www.nuget.org/packages/Nuke.MSBuildLocator/) but not `Microsoft.Build.Locator`.

Can we put metadata into the package so it turns up under that search?

**Comment by YuliiaKovalova** [comment]
@rainersigwald , could you check if the search returns now the desirable outcome:
![image](https://github.com/microsoft/MSBuildLocator/assets/95473390/8ef77122-5cbb-467c-ba1b-649d27970aee)

**Comment by rainersigwald** [comment]
Boo, it looks like it's case-sensitive:
![image](https://github.com/microsoft/MSBuildLocator/assets/3347530/ea8c06fd-48d9-4009-b00d-5b531ce4a1ea)
