### ISSUE TITLE
Any plan to publish the package to nuget.org?

### ISSUE THREAD

**Issue by vicancy** [Microsoft/MSBuildLocator#11]
So that our GA NuGet packages can reference it. https://github.com/dotnet/docfx/issues/2391

**Comment by AndyGerlicher** [comment]
https://www.nuget.org/packages/Microsoft.Build.Locator/

Still preview version for now in case we get feedback on any issues.

**Comment by AndyGerlicher** [comment]
@vicancy we published a non-preview version today:
https://www.nuget.org/packages/Microsoft.Build.Locator/1.0.13
