### ISSUE TITLE
MSBuildLocator is not available in .NET Core

### ISSUE THREAD

**Issue by ehsan-keshavarzian** [microsoft/MSBuildLocator#144]
![image](https://user-images.githubusercontent.com/8175035/137414593-5a5940c0-46a4-4e04-b3bf-e6b3e6238759.png)

**Comment by ehsan-keshavarzian** [comment]
I actually started from .NET 5 and went down to >NET Core 2.0 and it was the same for all of them.
It happens when I use PackageReference. I downloaded the assembly and referenced it from disk and it works fine (netcoreapp3.1).

**Comment by Forgind** [comment]
What version of MSBuildLocator are you using? How are you referencing it?

I have a project (targeting net6.0, but it also worked when targeting other frameworks) with <PackageReference Include="Microsoft.Build.Locator" Version="1.4.1" />, and it works fine.
