### ISSUE TITLE
Updating from version 1.4.1 to 1.5.5 breaks Unit Tests on Mac only

### ISSUE THREAD

**Issue by sensslen** [microsoft/MSBuildLocator#183]
I just updated the locator nuget package from version 1.4.1 to version 1.5.5. This led to my Unit tests to fail on the mac only. I don't see how this could relate but hope somebody from the community is able to help.

See https://github.com/sensslen/nuget-license/pull/1 for more details.

**Comment by Forgind** [comment]
I'm guessing this is the same as https://github.com/microsoft/MSBuildLocator/issues/200.

Can you check if your dotnet executable is on your PATH? And if it's a symlink, can you make sure its target is the right dotnet?

**Comment by sensslen** [comment]
Apparently you seem to be right. Moving from `actions/setup-dotnet@v2` to `actions/setup-dotnet@v3` resolved the problem.
