### ISSUE TITLE
Doesn't work on Apple M2

### ISSUE THREAD

**Issue by bartofzo** [microsoft/MSBuildLocator#200]
Found out about this trying to build a docfx project on my MBP:
https://github.com/dotnet/docfx/issues/8502#issue-1620402347

When running a .NET core console app and calling MSBuildLocator.RegisterDefaults()
I get the following exception:

Unhandled exception. System.InvalidOperationException: Failed to find an appropriate version of .NET Core MSBuild. Call to hostfxr_resolve_sdk2 failed. There may be more details in stderr.
at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()
at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()
at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()
at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable1 source, Boolean& found) at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable1 source)
at Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults()
at Program.

OS: MacOS ventura 13.2.1, Apple M2 Pro
Never had this problem on an Intel machine so I suspect it is due to that. Any fix or workaround available?

**Comment by Forgind** [comment]
Can you check if your dotnet executable is on your PATH? And if it's a symlink, can you make sure its target is the right dotnet?

**Comment by bartofzo** [comment]
I think it is, but I'm no expert at these kinds of things. If i run dotnet --info from a terminal I get the following information:

`Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.2
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /opt/homebrew/Cellar/dotnet/7.0.100/libexec/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: arm64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [/opt/homebrew/Cellar/dotnet/7.0.100/libexec/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0 [/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0 [/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  DOTNET_ROOT       [/opt/homebrew/Cellar/dotnet/7.0.100/libexec]
`

Does that help?

**Comment by Forgind** [comment]
dotnet --info is somewhat smarter in finding an appropriate SDK...I've been thinking recently about how to adopt some of their tactics.

Can you try changing you PATH just before invoking MSBuildLocator?

Specifically, I think your dotnet executable should be in one of the folders above where it found the SDK, so something like /opt/homebrew/Cellar/dotnet/7.0.100/libexec. Can you change PATH via
export PATH=/opt/homebrew/Cellar/dotnet/7.0.100/libexec:$PATH

then try RegisterDefaults?

**Comment by Forgind** [comment]
Our check is very direct with looking for dotnet at the exact spot as indicated on the path, so if it's under that spot, it won't work. Where is your dotnet executable? My suggestion looks like it included a version, which I don't see in the path you added to your PATH.

**Comment by Akronae** [comment]
I have the same issue using the VSCode C# extension

```
Dotnet path: /Users/alex/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.9/dotnet
Activating C# standalone...
info: LanguageServerHost[0]
      Starting server...
No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
[Error - 9:46:18 PM] [LanguageServerHost]System.InvalidOperationException: Failed to find an appropriate version of .NET Core MSBuild. Call to hostfxr_resolve_sdk2 failed. There may be more details in stderr.
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.TryEnsureMSBuildLoadedAsync(String workingDirectory) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 119
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.OpenSolutionAsync(String solutionFilePath) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 79
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 136
```

dotnet --info:
```
.NET SDK:
 Version:   7.0.305
 Commit:    98e1b6c381

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.1
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.305/

Host:
  Version:      7.0.8
  Architecture: arm64
  Commit:       4b0550942d

.NET SDKs installed:
  6.0.411 [/usr/local/share/dotnet/sdk]
  7.0.302 [/usr/local/share/dotnet/sdk]
  7.0.305 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.19 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

echo $PATH | grep dotnet
```
/usr/local/share/dotnet/sdk/7.0.305
/usr/local/share/dotnet/dotnet
/usr/local/share/dotnet/dotnet
/usr/local/share/dotnet
~/.dotnet/tools
/Users/alex/.dotnet/tools
/Users/alex/.dotnet/tools
```

**Comment by bartofzo** [comment]
> dotnet --info is somewhat smarter in finding an appropriate SDK...I've been thinking recently about how to adopt some of their tactics.
> 
> Can you try changing you PATH just before invoking MSBuildLocator?
> 
> Specifically, I think your dotnet executable should be in one of the folders above where it found the SDK, so something like /opt/homebrew/Cellar/dotnet/7.0.100/libexec. Can you change PATH via export PATH=/opt/homebrew/Cellar/dotnet/7.0.100/libexec:$PATH
> 
> then try RegisterDefaults?

Doesn't work. Still the same error.

**Comment by Dorbmon** [comment]
I got same problem on Apple M2pro

**Comment by montoulieu** [comment]
Same here on a M2 Ultra. Works fine on my M1 Max MacBook.

**Comment by YuliiaKovalova** [comment]
This one can be related to this issue 
https://github.com/dotnet/msbuild/issues/9038

@montoulieu , @Dorbmon , may I ask you to probe this workaround while we are working on the complex fix?
https://github.com/microsoft/vscode-dotnettools/issues/120#issuecomment-1640892593

**Comment by YuliiaKovalova** [comment]
The issue is fixed. Pending release.

**Comment by TownshendHill** [comment]
Apologies, but I have the same exact issue happening, only that it's on Apple M1 Max.

Reference:
`dotnet --version
7.0.100`

```
dotnet --info
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.5
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /opt/homebrew/Cellar/dotnet/7.0.100/libexec/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: arm64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [/opt/homebrew/Cellar/dotnet/7.0.100/libexec/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0 [/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0 [/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  DOTNET_ROOT       [/opt/homebrew/Cellar/dotnet/7.0.100/libexec]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

Notes:
 - I can run dotnet commands directly on terminal with no issues, but when run with vscode, below popup appears:
<img width="1018" alt="image" src="https://github.com/microsoft/MSBuildLocator/assets/44184686/e00d715e-e952-48db-8ce5-fd57e21e09c0">

-  VScode is unable to create any new projects (nothing happens like this issue)
- When opening a folder containing .cs and .csproj files, there is no Solution Explorer

Please let me know if there's further testing needed on my end, or to open a new issue. Cheers.

**Comment by YuliiaKovalova** [comment]
Hi @TownshendHill,

Thank you for reporting it.
The described issue seems to be related to this ticket from the extension repo: https://github.com/dotnet/vscode-csharp/issues/6461

There is no requested work for MSBuildLocator so far, so please track the progress in the referenced bug.
