### ISSUE TITLE
Pull Request workflow releases new version?

### ISSUE THREAD

**Issue by MichielOda** [microsoft/MSBuildLocator#249]
With Dependabot I noticed that there was a new version for the 'Microsoft.Build.Locator'. As it jumped from 1.6.1 to 1.6.10, I was curious to why there are suddenly 9 new versions. To my surprise I didn't saw any of the other tags, let alone this new version. 
Then I saw that there was a pull request #248 that changed the version number. Apparently this is enough to run the full workflow and release new versions without any tagging?

**Comment by rainersigwald** [comment]
> As it jumped from 1.6.1 to 1.6.10, I was curious to why there are suddenly 9 new versions.

That's not quite accurate. There's one new published version, which includes 9 commits. This repo uses https://github.com/dotnet/Nerdbank.GitVersioning to compute a version number based on "git height".

> Then I saw that there was a pull request . . . Apparently this is enough to run the full workflow and release new versions without any tagging?

To be super clear this is _not_ what is happening: creating a PR does not push a package anywhere.

**Comment by MichielOda** [comment]
> > As it jumped from 1.6.1 to 1.6.10, I was curious to why there are suddenly 9 new versions.
> 
> That's not quite accurate. There's one new published version, which includes 9 commits. This repo uses https://github.com/dotnet/Nerdbank.GitVersioning to compute a version number based on "git height".

Thanks for clarifying! 

> > Then I saw that there was a pull request . . . Apparently this is enough to run the full workflow and release new versions without any tagging?
> 
> To be super clear this is _not_ what is happening: creating a PR does not push a package anywhere.

I assumed so, but couldn't see any tags or releases with 1.6.10, so wanted to be sure that this is a correct released version before updating.

Thanks for the quick response!
