### ISSUE TITLE
Run MSBuildLocator.RegisterInstance throw exception

### ISSUE THREAD

**Issue by animalisme** [microsoft/MSBuildLocator#287]
I want to use MSBuildWorkspace to load the solution structure automatically, so i use the MSBuildLocator to init first, but now it throw exception when run into `MSBuildLocator.RegisterInstance(instance);`.
My visual IDE is vs2022 community,  project framework is .net8.0. 
My code is as 
` var instance = MSBuildLocator.QueryVisualStudioInstances().First(x=>x.Version.Major == 8);
 MSBuildLocator.RegisterInstance(instance);
 MSBuildLocator.RegisterDefaults();
 MSBuildWorkspace workspace = MSBuildWorkspace.Create();`

The exception message as follow: 

Microsoft.Build.Locator.MSBuildLocator.RegisterInstance was called, but MSBuild assemblies were already loaded.
Ensure that RegisterInstance is called before any method that directly references types in the Microsoft.Build namespace has been called.
This dependency arises from when a method is just-in-time compiled, so it breaks even if the reference to a Microsoft.Build type has not been executed.
For more details, see aka.ms/RegisterMSBuildLocator
Loaded MSBuild assemblies: Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Anyone can help me?

**Comment by animalisme** [comment]
@YuliiaKovalova ,thank you for your reply.But it doesn't work, in fact, it throw exception when it run to 
`MSBuildLocator.RegisterInstance(instance);`
I use `MSBuildLocator.QueryVisualStudioInstances()` to get VisualStudio Instances ,there is only one instance i got, i am not sure whether it is a correct msbuild instance.

**Comment by animalisme** [comment]
The instance.MSBuildPath is : "C:\Program Files\dotnet\sdk\8.0.202", and the instance DiscoveryType = DotNetSdk, and VisualStudioRootPath = "C:\\Program Files\\dotnet\\sdk\\8.0.202"。

**Comment by YuliiaKovalova** [comment]
@rainersigwald, do you have any ideas what can be wrong here?

**Comment by rainersigwald** [comment]
@animalisme Can you share the whole function that calls MSBuildLocator? And your project file?

**Comment by YuliiaKovalova** [comment]
Close issue due to lack of information.
Feel free to reopen if it is still relevant to you.
