### ISSUE TITLE
DevConsole instances for preview VS have the wrong version

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/MSBuildLocator#31]
When the environment variable `VSCMD_VER` is set to a prerelease version such as `15.7.0-pre.4.0` (on my current internal build, but these are available externally as well), `Version.TryParse` fails to parse it and we fall back to `VisualStudioVersion`, which is stuck at `15.0`. That causes the returned instance to report its version as `15.0`, which may lead an upstream consumer to incorrectly reject it.

**Comment by DustinCampbell** [comment]
Isn't this fixed now?

**Comment by rainersigwald** [comment]
Yes, fixed by #32.
