### ISSUE TITLE
Query options and sorting

### ISSUE THREAD

**Issue by clairernovotny** [microsoft/MSBuildLocator#68]
As far as I've seen, there's no way to sort or filter on VS options.

The following would be useful:

- Specify 2019 or 2017
- Preview or Stable
- Sort (ascending/descending, can be combined with preview/stable)

**Comment by rainersigwald** [comment]
The philosophy so far has been to push this onto the calling code, allowing it to get a list of options and filter/sort that in its own way.

https://github.com/microsoft/MSBuildLocator/blob/8b5c58f5842f58ebf860ece96ac0f6924df839b1/samples/BuilderApp/Program.cs#L26-L27

Do you think there's a better API that we could provide? What would that look like?

**Comment by onovotny** [comment]
The problem with "Ask what to use" is that it may not be interactive. 

From an API perspective, I think filters could be added to the query option. It would make it declarative, "give me 2019 or return emtpy if not found"

**Comment by onovotny** [comment]
Another idea, which could be combined with the query option, is to add additional properties to the instance objects, for the version number and channel name.

**Comment by rainersigwald** [comment]
I'd be on board with adding fields to our object to make filtering easier. Unfortunately, the things you're interested in don't seem to be available in [`ISetupInstance2`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.setup.configuration.isetupinstance2).

Adding filtering options to the query doesn't strike me as better than letting the caller do it, though.

**Comment by onovotny** [comment]
Does one of those at least indicate the channel name & stable/pre-release-ness? That'd be a good starting point.

**Comment by rainersigwald** [comment]
Not that I can see. The only "properties" I see are:

```
campaignId: 1060713956.1557239266
setupEngineFilePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installershell.exe
nickname:
channelManifestId: VisualStudio.16.Release/16.1.1+28922.388
```

**Comment by onovotny** [comment]
How does `vswhere` do it then, there must be a way? It has a `-prerelease` flag (and skips those by default).

**Comment by jnm2** [comment]
The ability to filter to require workloads is important, too. Finding the wrong VS Build Tools installation was the cause of the `The SDK 'Microsoft.NET.Sdk' specified could not be found` failure for us, and I see a couple issues in this repo with that same message.

On a build server with:

- VS Build Tools 2019 with no workloads and only certain components installed
- VS Build Tools 2022 with .NET web and desktop workloads

`RegisterDefaults()` will pick 2019 and not be able to work with `Microsoft.CodeAnalysis.Workspaces.MSBuild`.

**Comment by jnm2** [comment]
Would you accept a PR to expose the information in [`ISetupInstance2.GetPackages()`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.setup.configuration.isetupinstance2.getpackages) through `VisualStudioInstance` and let folks do their own filtering?

**Comment by rainersigwald** [comment]
> Would you accept a PR to expose the information in [`ISetupInstance2.GetPackages()`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.setup.configuration.isetupinstance2.getpackages) through `VisualStudioInstance` and let folks do their own filtering?

Yes.



> Optionally, new APIs roughly like this could be added to make this (hopefully common) usage easier:
> 
> ```cs
> MSBuildLocator.RegisterLatest(new VisualStudioInstanceQueryOptions
> {
>     RequiredComponents = { RequiredComponent.DotNetSdk },
> });
> ```

That is slick--but where are the components defined? I'd rather not have to replicate lists from VS Setup if we can delegate to it.

**Comment by baronfel** [comment]
There's a similar problem for locating and selecting preview .NET SDKs, as logged in https://github.com/tintoy/msbuild-project-tools-server/issues/94.

The current logic asks the hostfxr to list SDKs, but the hostfxr call doesn't seem to support listing previews through the APIs. I haven't checked yet to see if the rollforward selection environment variables can influence this call, though.  There's a separate hostfxr call that can do _selection_ of the correct SDK including previews, but that doesn't seem to be a 1;1 match with the call we're using now, so we may need the runtime to fill this gap.

**Comment by YuliiaKovalova** [comment]
Hi @clairernovotny,

The ability to query preview versions was added in the recent package:
https://www.nuget.org/packages/Microsoft.Build.Locator/1.7.8

Please let us know if it partially resolves your request.

**Comment by YuliiaKovalova** [comment]
Feel free to reopen and specify what else is missing for your current needs.
