### ISSUE TITLE
NuGet package description

### ISSUE THREAD

**Issue by nnpcYvIVl** [microsoft/MSBuildLocator#69]
The package description at https://www.nuget.org/packages/Microsoft.Build.Locator/ says
```
Package that assists in locating and using an installed version of MSBuild 15.
```

Should the reference to version 15 be changed to simply say MSBuild?
```
Package that assists in locating and using an installed version of MSBuild.
```

**Comment by rainersigwald** [comment]
Yes, that would be a good change.

We might want to say something about

> a copy of MSBuild installed as part of Visual Studio 2017 or higher or .NET Core SDK 2.1 or higher.
