### ISSUE TITLE
Shouldn't the NuGet package just be called "Microsoft.Build.Locator"?

### ISSUE THREAD

**Issue by DustinCampbell** [Microsoft/MSBuildLocator#7]

**Comment by KirillOsenkov** [comment]
Is there a NuGet package for MSBuildLocator already? How do I reference it? I haven't found anything on Nuget.org.

**Comment by DustinCampbell** [comment]
It's on myget: https://dotnet.myget.org/feed/msbuild/package/nuget/Microsoft.Build.MSBuildLocator

**Comment by KirillOsenkov** [comment]
@AndyGerlicher
