### ISSUE TITLE
64-bit runtime does not return correct path,

### ISSUE THREAD

**Issue by zeptoZB** [microsoft/MSBuildLocator#70]
64-bit runtime does not return correct path, is missing add @"\amd64".

**Comment by rainersigwald** [comment]
Can you clarify what you're asking? Is it "when invoked from a 64-bit process, automatically find the 64-bit assemblies"?

Are you noticing a specific problem? MSBuild's API assemblies are AnyCPU/MSIL, so they should load and run just fine in a 64-bit process.

**Comment by zeptoZB** [comment]
You're right! Comparing the directories basically the difference is MSBuild.exe.
