### ISSUE TITLE
Microsoft.Build.Locator package should be signed

### ISSUE THREAD

**Issue by ryanbrandenburg** [microsoft/MSBuildLocator#71]
I've been writing a tool which uses Microsoft.Build.Locator, and now that it comes closer to time to ship it our pipeline complained because the dll isn't signed. I confirmed this by comparing the "properties" view of `Microsoft.Build.Locator.dll` vs a known signed dll and seeing that Locator was missing a "Digital Signatures" tab.

**Comment by rainersigwald** [comment]
@ryanbrandenburg Can you please try version 1.2.6 from our MyGet? If that meets your needs we will push it to nuget.org.

https://dotnet.myget.org/feed/msbuild/package/nuget/Microsoft.Build.Locator/1.2.6

**Comment by ryanbrandenburg** [comment]
I was able to put it through our pipeline and it appears to be signed, so we're good from that perspective. When can we get it updated on nuget?

**Comment by rainersigwald** [comment]
https://www.nuget.org/packages/Microsoft.Build.Locator/1.2.6 is now live
