### ISSUE TITLE
MSBuildLocator.RegisterDefaults() throws on Mono 

### ISSUE THREAD

**Issue by ionoy** [microsoft/MSBuildLocator#72]
Hello guys!

I'm using `Microsoft.Build.Locator 1.2.2` NuGet package in my `net472` console application. This application is executed on macOS using `mono`. The goal is to analyze a solution (.sln) with `MSBuildWorkspace`. 

`MSBuildLocator.RegisterDefaults()` fails with `PlatformNotSupportedException` because there is a call from `VisualStudioLocationHelper.GetQuery()` to `Marshal.GetTypeFromCLSID` which is not supported on Mono (https://github.com/mono/mono/blob/master/mcs/class/corlib/System.Runtime.InteropServices/Marshal.cs#L838)

Am I misunderstanding something or it is impossible to use `Microsoft.Build.Locator` on Mono? 

P.S. .NET Core doesn't work for me, because Core MSBuildWorkspace fails to load non-Core solutions.

**Comment by rainersigwald** [comment]
You're correct. MSBuildLocator does not currently support Mono: #41.

I'm not aware of a great way to deal with this situation at the moment. I expect things to get better in the future with the advent of [.NET 5](https://devblogs.microsoft.com/dotnet/introducing-net-5/).
