### ISSUE TITLE
Consider using Assembly.Load instead of Assembly.LoadFrom

### ISSUE THREAD

**Issue by KirillOsenkov** [Microsoft/MSBuildLocator#8]
Here:
https://github.com/Microsoft/MSBuildLocator/blob/master/src/MSBuildLocator/MSBuildLocator.cs#L75

consider using:
```
if (File.Exists(targetAssembly))
{
    var name = AssemblyName.GetAssemblyName(targetAssembly);
    Assembly.Load(name);
}
```

instead of Assembly.LoadFrom.

LoadFrom is not great because it loads into the LoadFrom context and has other repercussions. You almost always want to load assemblies using the trick above.

GetAssemblyName stashes the full path to the assembly in the _Codebase field:
http://referencesource.microsoft.com/#mscorlib/system/reflection/assemblyname.cs,45
It is then used as a hint to the loader to load it from that location.

cc @davkean

**Comment by davkean** [comment]
Since 2.0, LoadFrom will respect the Load context (GAC, search paths) before falling back to the LoadFrom context that code shouldn't be needed.

**Comment by KirillOsenkov** [comment]
Hmm, I could swear we saw issues in MonoDevelop (.NET 4.6) resulting from using LoadFrom, but I can't remember now what it was. OK for now this doesn't seem to be a problem, so good!
