### ISSUE TITLE
Failure to load NuGet SDKs in dotnet format

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/MSBuildLocator#88]
> @rainersigwald Rainer Sigwald FTE if you run the command below
> 
> ```
> dotnet tool install -g dotnet-format --version 4.0.121404 --add-source https://dotnet.myget.org/F/format/api/v3/index.json
> ```
> 
> and then run this command over this repo: https://github.com/dotnet/tye
> 
> ```
> dotnet-format -w tye.sln -v diag
> ```
> 
> you should get a bin log. Would be very curious to get a second opinion on what is happening here

from https://github.com/dotnet/format/issues/584#issuecomment-614135659

I reproduce with these instructions but haven't dug in.

**Comment by JoeRobich** [comment]
@sharwell Found that the NuGetSdkResolver wouldn't load unless we added a local dependency on Newtonsoft.Json. I'm not yet sure why the AssemblyLoader that we use couldn't resolve it from the SDK folder as it does other MSBuild dependencies.

**Comment by YuliiaKovalova** [comment]
@rainersigwald , it this issue still relevant?
![image](https://github.com/microsoft/MSBuildLocator/assets/95473390/c6ec9a26-acc5-4e99-b121-5e6eccb92241)

**Comment by baronfel** [comment]
`dotnet format` is shipped in the SDK these days, and I've successfully used it on many projects - I'm leaning towards this is probably not relevant anymore.

**Comment by JoeRobich** [comment]
Can confirm that we have not had recent reports of this issue.

**Comment by YuliiaKovalova** [comment]
Close as not relevant anymore.
Thank you for your responses!
